/* Gemeinsame Themen-Taxonomie — genutzt vom Verzeichnis (app.js),
   der Themenfeld-Seite (themen.js), der Startseite und dem
   Mitmachen-Formular (join.js). Reihenfolge = Anzeigereihenfolge.
   Orientiert an den Sections der EPSS, umgemünzt auf journalistisch
   relevante Themen und Politikfelder.
   Muss synchron bleiben mit: data/experts.schema.json (enum),
   scripts/issue_to_profile.py (TOPICS) und .github/ISSUE_TEMPLATE/profil.yml
   — scripts/validate.py prüft das. */
window.PSW_TOPICS = [
  { name: 'Wahlen & Wahlverhalten', color: '#2b44df',
    desc: 'Bundestags-, Landtags- und Europawahlen, Wahlkampf, Wählerwanderung, Wahlbeteiligung.' },
  { name: 'Parteien & Parteienwettbewerb', color: '#e03e1f',
    desc: 'Parteiensystem, Parteistrategien und -organisation, neue Parteien, Koalitionsoptionen.' },
  { name: 'Öffentliche Meinung & Umfragen', color: '#00805f',
    desc: 'Einstellungsforschung, Sonntagsfrage, Meinungsklima, Polarisierung.' },
  { name: 'Politische Kommunikation', color: '#7a3ff2',
    desc: 'Wahlkampfkommunikation, politische Rhetorik, Framing, Medien und Politik.' },
  { name: 'Digitale Medien & Desinformation', color: '#d61f69',
    desc: 'Social Media, Desinformation, Plattformregulierung, digitale Öffentlichkeit.' },
  { name: 'Künstliche Intelligenz & Digitalpolitik', color: '#0f4c81',
    desc: 'KI in Politik und Wahlkampf, KI-Regulierung, Daten- und Plattformpolitik.' },
  { name: 'Demokratie & Autokratisierung', color: '#b97e00',
    desc: 'Demokratiequalität, demokratische Resilienz, autoritäre Tendenzen weltweit.' },
  { name: 'Extremismus & Radikalisierung', color: '#0d7ea8',
    desc: 'Rechtsextremismus, Islamismus, Verschwörungsideologien, Prävention.' },
  { name: 'Protest & Soziale Bewegungen', color: '#c2410c',
    desc: 'Demonstrationen, ziviler Ungehorsam, Klimabewegung, Mobilisierung.' },
  { name: 'Politische Beteiligung & Repräsentation', color: '#6d28d9',
    desc: 'Wahlrecht, Bürgerräte, politisches Engagement, Repräsentationslücken.' },
  { name: 'Geschlecht, Gleichstellung & Diversität', color: '#be185d',
    desc: 'Frauen in der Politik, Parität, LGBTIQ*-Politik, Antidiskriminierung.' },
  { name: 'Migration & Integration', color: '#a16207',
    desc: 'Asyl- und Einwanderungspolitik, Integration, Einstellungen zu Migration.' },
  { name: 'Europäische Union', color: '#1d4ed8',
    desc: 'EU-Institutionen, Europawahlen, Erweiterung, europäische Integration.' },
  { name: 'Internationale Beziehungen & Diplomatie', color: '#4d7c0f',
    desc: 'Außenpolitik, internationale Organisationen, Geopolitik, transatlantische Beziehungen.' },
  { name: 'Krieg, Konflikt & Sicherheit', color: '#7f1d1d',
    desc: 'Bewaffnete Konflikte, Verteidigungspolitik, NATO, Friedensprozesse.' },
  { name: 'Entwicklungspolitik & Globaler Süden', color: '#b45309',
    desc: 'Entwicklungszusammenarbeit, globale Ungleichheit, Nord-Süd-Beziehungen.' },
  { name: 'Regierung, Koalitionen & Parlamente', color: '#9333ea',
    desc: 'Regierungsbildung, Koalitionsverhandlungen, Gesetzgebung, Parlamentarismus.' },
  { name: 'Föderalismus & Landespolitik', color: '#0e7490',
    desc: 'Bund-Länder-Verhältnis, Landtagswahlen, Politik der Bundesländer.' },
  { name: 'Lokal- & Kommunalpolitik', color: '#166534',
    desc: 'Kommunalwahlen, Stadtpolitik, kommunale Selbstverwaltung, Bürgermeister:innen.' },
  { name: 'Verwaltung & Staatsmodernisierung', color: '#475569',
    desc: 'Öffentliche Verwaltung, Bürokratieabbau, Digitalisierung des Staates.' },
  { name: 'Recht, Justiz & Verfassung', color: '#713f12',
    desc: 'Verfassungsgerichte, Rechtsstaat, Justizpolitik, Grundrechte.' },
  { name: 'Interessengruppen & Lobbyismus', color: '#be123c',
    desc: 'Verbände und NGOs, Lobbyregulierung, Einfluss auf die Gesetzgebung.' },
  { name: 'Wirtschafts- & Finanzpolitik', color: '#b91c1c',
    desc: 'Haushalt, Steuern, Schuldenbremse, Wirtschaftsordnung, Inflation.' },
  { name: 'Sozialpolitik & Wohlfahrtsstaat', color: '#0f766e',
    desc: 'Rente, Bürgergeld, Pflege, Arbeitsmarkt, soziale Ungleichheit.' },
  { name: 'Gesundheitspolitik', color: '#15803d',
    desc: 'Gesundheitssystem, Krankenversicherung, Pandemiepolitik, Prävention.' },
  { name: 'Bildungs- & Wissenschaftspolitik', color: '#c026d3',
    desc: 'Schul- und Hochschulpolitik, Forschungsförderung, Wissenschaftsfreiheit.' },
  { name: 'Klima-, Umwelt- & Energiepolitik', color: '#15703b',
    desc: 'Klimaschutz, Energiewende, Umweltregulierung, internationale Klimapolitik.' },
  { name: 'Politische Theorie & Ideengeschichte', color: '#5b21b6',
    desc: 'Demokratietheorie, Gerechtigkeit, politische Ideologien, Ideengeschichte.' },
  { name: 'Vergleichende Politikwissenschaft', color: '#0369a1',
    desc: 'Politische Systeme im Ländervergleich, Regimeforschung, vergleichende Politikfeldanalyse.' },
  { name: 'Methoden, Daten & Prognosen', color: '#334155',
    desc: 'Umfragemethodik, Wahlprognosen, Experimente, Computational Social Science.' }
];
